### ISSUE TITLE
X11 gestures are not used: the default touchegg options are used

### ISSUE THREAD

**Issue by LorenzoBettini** [JoseExposito/gnome-shell-extension-x11gestures#22]
### Describe the bug

I've installed Touchegg in Ubuntu 21.04 by using the provided .deb file, and made sure it works (the default gestures are used). Then, I installed the X11 gestures extensions and restarted, but still the default gestures from touchegg are used, not the expected Gnome ones (if that's what this extension is supposed to do).

### Expected behaviour

I'd expect the Gnome gestures provided by this extension (e.g., 3 fingers swipe for show activities, etc.)

### Actual behaviour

The default gestures from touchegg are used (e.g., 3 fingers swipe for maximizing and minimizing)

### Logs

I see no specific information when running the below command

```
$ journalctl -f -o cat /usr/bin/gnome-shell

```

### Your environment

 * Extension version: the one installed from https://extensions.gnome.org/extension/4033/x11-gestures/
 * Touchégg version: 2.0.11
 * Operating System: Ubuntu 21.04
 * GNOME Shell Version: 3.38

**Comment by LorenzoBettini** [comment]
Actually if I run this

```
journalctl | grep gestures
```

I see these lines which from what I understand mean that the extension is working correctly, but still, as I said above, the default touchegg gestures are used:

```
gnome-shell[2163]: [x11gestures@joseexposito.github.io] Extension enabled
gnome-shell[2163]: [x11gestures@joseexposito.github.io] Building entry point for GNOME Shell 3.38.4
gnome-shell[2163]: [x11gestures@joseexposito.github.io] Connecting to Touchégg daemon
gnome-shell[2163]: [x11gestures@joseexposito.github.io] Hooking global switch desktop gestures
gnome-shell[2163]: [x11gestures@joseexposito.github.io] Creating a new SwipeTracker336
gnome-shell[2163]: [x11gestures@joseexposito.github.io] Connecting Touchégg client signals
gnome-shell[2163]: [x11gestures@joseexposito.github.io] Hooking activities view switch desktop gestures
gnome-shell[2163]: [x11gestures@joseexposito.github.io] Creating a new SwipeTracker336
gnome-shell[2163]: [x11gestures@joseexposito.github.io] Connecting Touchégg client signals
gnome-shell[2163]: [x11gestures@joseexposito.github.io] Connection with Touchégg established
```

**Comment by LorenzoBettini** [comment]
> Hi Lorenzo,
> 

Hi Jose, thanks for the quick answer, see my answers below

> The logs suggest that everything is working as expected. Do you mind to attach your configuration file placed at `~/.config/touchegg/touchegg.conf`, please?

sure, here it is, from what I understand it's the default one:

```
<touchégg>

  <settings>
    <!--
      Delay, in milliseconds, since the gesture starts before the animation is displayed.
      Default: 150ms if this property is not set.
      Example: Use the MAXIMIZE_RESTORE_WINDOW action. You will notice that no animation is
      displayed if you complete the action quick enough. This property configures that time.
    -->
    <property name="animation_delay">150</property>

    <!--
      Percentage of the gesture to be completed to apply the action. Set to 0 to execute actions unconditionally.
      Default: 20% if this property is not set.
      Example: Use the MAXIMIZE_RESTORE_WINDOW action. You will notice that, even if the
      animation is displayed, the action is not executed if you did not move your fingers far
      enough. This property configures the percentage of the gesture that must be reached to
      execute the action.
    -->
    <property name="action_execute_threshold">20</property>

    <!--
      Global animation colors can be configured to match your system colors using HEX notation:

        <color>909090</color>
        <borderColor>FFFFFF</borderColor>

      You can also use auto:

        <property name="color">auto</property>
        <property name="borderColor">auto</property>

      Notice that you can override an specific animation color.
    -->
    <property name="color">auto</property>
    <property name="borderColor">auto</property>
  </settings>

  <!--
    Configuration for every application.
  -->
  <application name="All">
    <gesture type="SWIPE" fingers="3" direction="UP">
      <action type="MAXIMIZE_RESTORE_WINDOW">
        <animate>true</animate>
      </action>
    </gesture>

    <gesture type="SWIPE" fingers="3" direction="DOWN">
      <action type="MINIMIZE_WINDOW">
        <animate>true</animate>
      </action>
    </gesture>

    <gesture type="SWIPE" fingers="3" direction="LEFT">
      <action type="TILE_WINDOW">
        <direction>left</direction>
        <animate>true</animate>
      </action>
    </gesture>

    <gesture type="SWIPE" fingers="3" direction="RIGHT">
      <action type="TILE_WINDOW">
        <direction>right</direction>
        <animate>true</animate>
      </action>
    </gesture>

    <gesture type="PINCH" fingers="3" direction="IN">
      <action type="CLOSE_WINDOW">
        <animate>true</animate>
        <color>F84A53</color>
        <borderColor>F84A53</borderColor>
      </action>
    </gesture>

    <gesture type="SWIPE" fingers="4" direction="UP">
      <action type="CHANGE_DESKTOP">
        <direction>auto</direction>
        <animate>true</animate>
        <animationPosition>auto</animationPosition>
      </action>
    </gesture>

    <gesture type="SWIPE" fingers="4" direction="DOWN">
      <action type="CHANGE_DESKTOP">
        <direction>auto</direction>
        <animate>true</animate>
        <animationPosition>auto</animationPosition>
      </action>
    </gesture>

    <gesture type="SWIPE" fingers="4" direction="RIGHT">
      <action type="SEND_KEYS">
        <repeat>false</repeat>
        <modifiers>Super_L</modifiers>
        <keys>S</keys>
        <on>begin</on>
      </action>
    </gesture>

    <gesture type="PINCH" fingers="4" direction="OUT">
      <action type="SHOW_DESKTOP">
        <animate>true</animate>
      </action>
    </gesture>

    <gesture type="PINCH" fingers="4" direction="IN">
      <action type="SEND_KEYS">
        <repeat>false</repeat>
        <modifiers>Super_L</modifiers>
        <keys>A</keys>
        <on>begin</on>
      </action>
    </gesture>

    <gesture type="TAP" fingers="2">
      <action type="MOUSE_CLICK">
        <button>3</button>
        <on>begin</on>
      </action>
    </gesture>

    <gesture type="TAP" fingers="3">
      <action type="MOUSE_CLICK">
        <button>2</button>
        <on>begin</on>
      </action>
    </gesture>
  
<gesture type="SWIPE" fingers="4" direction="UP"><action type="GNOME_SHELL"></action></gesture>
<gesture type="SWIPE" fingers="4" direction="DOWN"><action type="GNOME_SHELL"></action></gesture>
<gesture type="SWIPE" fingers="4" direction="UP"><action type="GNOME_SHELL"></action></gesture>
<gesture type="SWIPE" fingers="4" direction="DOWN"><action type="GNOME_SHELL"></action></gesture>
</application>

  <!--
    Configuration for specific applications.
  -->

  <application name="Google-chrome,Chromium-browser,Firefox">
    <gesture type="PINCH" fingers="2" direction="IN">
      <action type="SEND_KEYS">
        <repeat>true</repeat>
        <modifiers>Control_L</modifiers>
        <keys>KP_Subtract</keys>
        <decreaseKeys>KP_Add</decreaseKeys>
      </action>
    </gesture>

    <gesture type="PINCH" fingers="2" direction="OUT">
      <action type="SEND_KEYS">
        <repeat>true</repeat>
        <modifiers>Control_L</modifiers>
        <keys>KP_Add</keys>
        <decreaseKeys>KP_Subtract</decreaseKeys>
      </action>
    </gesture>
  </application>

</touchégg>
```


> 
> PS - On Ubuntu, you can install Touchégg from the PPA, so you don't need to worry about updates: https://github.com/JoseExposito/touchegg#ubuntu-debian-and-derivatives

I had tried that but I get this error, and then I get the old one from the standard Ubuntu repository. Of course, I first uninstalled the old one and cleared the touchegg.conf before installing the deb file manually:

```
sudo add-apt-repository ppa:touchegg/stable

Repository: 'deb http://ppa.launchpad.net/touchegg/stable/ubuntu/ hirsute main'
Description:
Latest stable version of Touchégg for all Ubuntu flavours.

Touchégg is an app that runs in the background and transform the gestures you make on your touchpad or touchscreen into visible actions in your desktop. Learn more at https://github.com/JoseExposito/touchegg
More info: https://launchpad.net/~touchegg/+archive/ubuntu/stable
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/touchegg-ubuntu-stable-hirsute.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/touchegg-ubuntu-stable-hirsute.list
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 364, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
  File "/usr/bin/add-apt-repository", line 357, in main
    shortcut.add()
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 222, in add
    self.add_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 398, in add_key
    if not all((self.trustedparts_file, self.trustedparts_content)):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in trustedparts_content
    key = self.lpppa.getSigningKeyData()
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 605, in __call__
    response, content = self.root._browser._request(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 438, in _request
    raise error
lazr.restfulclient.errors.ServerError: HTTP Error 500: Internal Server Error
Response headers:
---
connection: close
content-length: 30
content-type: text/plain;charset=utf-8
date: Tue, 12 Oct 2021 17:18:13 GMT
server: gunicorn/19.8.1
status: 500
x-lazr-oopsid: OOPS-b0bc5dcd565fb96c2460f872e5229acd
x-powered-by: Zope (www.zope.org), Python (www.python.org)
x-request-id: fbc31085-9739-49fe-bee0-735e957a4d2b
x-vcs-revision: 8a94da2fac127f5e46a49fd1140e43759d578803
---
Response body:
---
b'GPGKeyTemporarilyNotFoundError'
---

```

**Comment by LorenzoBettini** [comment]
OK, then it's a feature not a bug. I'm on Gnome 3.38 and the four fingers swipe switch the workspace as you say.
I thought this extension would have also mimick the new Gnome 40 behavior of 3 fingers but apparently, I was wrong :)
I guess I just have to customize the default gestures.
I'm really sorry for the noise!
I guess we can close it
P.S. the PPA is now working.

**Comment by JoseExposito** [comment]
No problem at all, glad to help you. Closing the issue.
